
language: rust
sudo: false

env:
  global:
    - secure: "PdLSLIwcxQynRSxfkZrhYPQu8goMpbO3BUoIvUohRzF2xYFB6sS/4+uxyzCuy85TV+2Q6TYdh/G3GDcRVU24G4mMIV2AH3PwiRmC/bzclqbj6CWtBlgHkKP4WYsIaqxuLl4X/7W8EbNjAqW3bD/WuzESGbY26v3pu+MLoQvxduA="
script:
- cargo build
- cargo test
- cargo test --no-default-features --features "blist"
- cargo test --no-default-features --features "enum_set"
- cargo test --no-default-features --features "immut_slist"
- cargo test --no-default-features --features "interval_heap"
- cargo test --no-default-features --features "linked_hash_map"
- cargo test --no-default-features --features "lru_cache"
- cargo test --no-default-features --features "tree_map"
- cargo test --no-default-features --features "proto"
- cargo test --no-default-features --features "string_joiner"
- cargo doc

after_success:
  - test "$TRAVIS_PULL_REQUEST" == false && test "$TRAVIS_BRANCH" == "master" && bash deploy-docs.sh
