[package]

name = "collect"
version = "0.0.5"
license = "MIT/Apache-2.0"
description = "An experimental extension of std::collections"
authors = ["Alexis Beingessner <a.beingessner@gmail.com>",
           "Sebastian Gesemann <s.gesemann@gmail.com>"]

[dependencies]
traverse = "0.0.2"
